<#
.SYNOPSIS
  PreToolUse guard for Write / Edit.

.DESCRIPTION
  Blocks edits to files that must never be modified by an agent:
    - real env files holding secrets (.env, .env.local, .env.production)
    - Prisma migrations that have already been applied (forward-only rule)
    - generated or vendored output (.next, node_modules, src/components/ui)

  Contract:
    stdin  : PreToolUse hook JSON
    exit 0 : allow
    exit 2 : block; stderr is fed back to Claude as the reason
#>

$ErrorActionPreference = 'Stop'

function Allow { exit 0 }
function Block([string]$Reason) { [Console]::Error.WriteLine($Reason); exit 2 }

# ── parse hook input; never fail closed on a parse problem ──────────────
try {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) { Allow }
    $hook = $raw | ConvertFrom-Json
} catch { Allow }

$filePath = $hook.tool_input.file_path
if ([string]::IsNullOrWhiteSpace($filePath)) { Allow }

$normalized = ($filePath -replace '\\', '/')
$leaf       = Split-Path $normalized -Leaf

# ── 1. environment files ────────────────────────────────────────────────
# .env.example is the documented, committed template — always allowed.
if ($leaf -like '.env*' -and $leaf -ne '.env.example') {
    Block @"
BLOCKED: $leaf holds real secrets and must be edited by hand.

If a new variable is needed:
  1. add it to .env.example with a comment and NO value
  2. add it to the Zod schema in src/lib/env.ts
  3. document it in docs/05-infrastructure.md section 2.3
  4. tell the developer to set the real value in .env.local themselves
"@
}

# ── 2. authored Prisma migrations ───────────────────────────────────────
# Migrations are forward-only (.claude/rules/40-database-and-prisma.md).
#
# But `prisma migrate dev --create-only` deliberately scaffolds a migration.sql
# containing nothing but "-- This is an empty migration." and expects you to
# write the SQL into it. That is the supported workflow for anything Prisma
# cannot express — generated columns, GIN indexes, extensions.
#
# So the test is not "is this a migration file" but "has this migration been
# AUTHORED yet". Strip comments and whitespace: if no SQL remains, it is an
# untouched scaffold and writing to it is the intended path.
if ($normalized -match 'prisma/migrations/.+/migration\.sql$') {
    $hasSql = $false
    if (Test-Path -LiteralPath $filePath) {
        $body = (Get-Content -LiteralPath $filePath -Raw -ErrorAction SilentlyContinue)
        if ($body) {
            # Drop full-line SQL comments, then check for any remaining content.
            $stripped = ($body -split "`r?`n" | Where-Object { $_ -notmatch '^\s*--' }) -join ''
            $hasSql = -not [string]::IsNullOrWhiteSpace($stripped)
        }
    }

    if ($hasSql) {
        Block @"
BLOCKED: $leaf already contains SQL, so it may have been applied somewhere.
Migrations are forward-only — editing one that has run corrupts the history.

To change the schema:
  1. edit prisma/schema.prisma
  2. run: npm run db:migrate -- --name <descriptive-name>
  3. commit schema.prisma AND the new migration together

To undo something already applied, write a NEW migration that reverts it.

If this migration is NOT yet applied and you are still authoring it, delete the
file and re-scaffold it:
  npx prisma migrate dev --create-only --name <name>
"@
    }
}

# ── 3. generated / vendored output ──────────────────────────────────────
$generated = @(
    @{ Pattern = '/\.next/';        Reason = 'build output — regenerate with npm run build' },
    @{ Pattern = '/node_modules/';  Reason = 'dependency code — change package.json instead' },
    @{ Pattern = '/\.prisma/';      Reason = 'generated client — run npx prisma generate' },
    @{ Pattern = '/coverage/';      Reason = 'test output — regenerate with npm run test' }
)
foreach ($g in $generated) {
    if ($normalized -match $g.Pattern) { Block "BLOCKED: $leaf is generated ($($g.Reason))." }
}

# shadcn primitives are generated by the CLI and must not be hand-edited
# (.claude/rules/60-ui-and-accessibility.md).
if ($normalized -match 'src/components/ui/.+\.tsx$') {
    Block @"
BLOCKED: src/components/ui/ holds generated shadcn primitives.

Do not hand-edit them. Either:
  - regenerate:  npx shadcn@latest add <component>
  - or wrap it in a new component under src/components/features/
"@
}

Allow
